# Generated by Django 3.2.16 on 2023-11-11 22:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('birthday', '0005_auto_20231112_0038'),
    ]

    operations = [
        migrations.RenameField(
            model_name='birthday',
            old_name='tag',
            new_name='tags',
        ),
    ]
